## Basic Setups to use OpenAI Gym with Colab

In [1]:
colab = True
if colab:
    !pip install swig
    !pip install gym[all]==0.21.0 pyvirtualdisplay > /dev/null 2>&1
    !apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1
    !apt-get update > /dev/null 2>&1
    !apt-get install cmake > /dev/null 2>&1
    !pip install --upgrade setuptools 2>&1
    !pip install ez_setup > /dev/null 2>&1
    !pip install pygame
    !pip install pyglet==1.5.27
    !pip install pyvirtualdisplay
    !pip install gym[box2d]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.2 MB/s eta 0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.6 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.4/374.4 kB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 81.7 MB/s eta 0:00:00
  Created wheel for box2d-py: filename=box2d_py-2.3.5-cp310-cp310-linux_x86_64.whl size=2812284 sha256=a5fe8e1979daa90908b3bde216438a7af7474e0139378b989bc1338f9e963e93
  Stored in directory: /root/.cache/pip/wheels/db/8f/6a/eaaadf056fba10a98d986f6dce954e6201ba3126926fc5ad9e
Successfully built box2d-py
  Attempting uninst

# 0. Connect google drive with Colab

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!ls

drive  sample_data


In [5]:
%cd /content/drive/MyDrive/Colab Notebooks/양인순 교수님/setting
!ls

/content/drive/MyDrive/Colab Notebooks/양인순 교수님/setting
chap1_setting.pdf   __pycache__  torch_test.py
Humanoid_expert.py  setup.ipynb  video


# 1. Introduction to Gym environment

## 1.1 Prerequisites

In [6]:
import gym
from gym.wrappers.record_video import RecordVideo
import glob
import io
import base64
from IPython.display import HTML
from pyvirtualdisplay import Display
from IPython import display as ipythondisplay

display = Display(visible=0, size=(1400, 900))
display.start()

"""
Utility functions to enable video recording of gym environment
and displaying it.
To enable video, just do "env = wrap_env(env)""
"""
def show_video(env_id):
    mp4list = glob.glob('video/'+env_id+'/*.mp4')
    if len(mp4list) > 0:
      mp4 = mp4list[0]
      video = io.open(mp4, 'r+b').read()
      encoded = base64.b64encode(video)
      ipythondisplay.display(HTML(data='''<video alt="test" autoplay
                  loop controls style="height: 400px;">
                  <source src="data:video/mp4;base64,{0}" type="video/mp4" />
              </video>'''.format(encoded.decode('ascii'))))
    else:
        print("Could not find video")


def wrap_env(env, env_id):
#    env = Monitor(env, './video', force=True)
    env=RecordVideo(env, './video/'+env_id,  episode_trigger = lambda episode_number: True)
    return env

Now, we can render Gtm environment!

If you run in jupyter, turn

```
colab = False
```

In [7]:
colab = True

## 1.2 Basic environments

In [8]:
import gym

# TODO : Render classic control problems below
# CartPole-v1
# MountainCar-v0
# Pendulum-v0
# Visit https://gym.openai.com/envs/#classic_control for more environments!

env_id = 'Acrobot-v1'

# Build environment with env ID!
env = gym.make(env_id)
if colab:
    env = wrap_env(env, env_id)

# Initialize environment
observation = env.reset()

for t in range(1000):
    env.render()

    # Randomly sample action from environment
    action = env.action_space.sample()

    # Simulate 1 step
    observation, reward, done, info = env.step(action)

    # done is used to check terminal condition
    if done:
      break;

# Close environment
env.close()

# Render environment
if colab:
    show_video(env_id)

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/record_video.py:78: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/Colab Notebooks/양인순 교수님/setting/video/Acrobot-v1 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/monitoring/video_reco

In [9]:
import gym

# TODO : Render Box2d environments below
# BipedalWalker-v3
# LunarLander-v2
# CarRacing-v0
# Visit https://gym.openai.com/envs/#box2d for more environments!

# display = Display(visible=0, size=(1400, 900))
# display.start()

env_id = 'CarRacing-v2'

# Build environment with env ID!
env = gym.make(env_id)
if colab:
    env = wrap_env(env, env_id)

# Initialize environment
observation = env.reset()

for t in range(1000):
    env.render()

    # Randomly sample action from environment
    action = env.action_space.sample()

    # Simulate 1 step
    observation, reward, done, info = env.step(action)

    # done is used to check terminal condition
    if done:
      break;

# Close environment
env.close()

# Render environment
if colab:
    show_video(env_id)

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/record_video.py:78: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/Colab Notebooks/양인순 교수님/setting/video/CarRacing-v2 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/monitoring/video_re

## 1.3 Robotics environment

In [10]:
# Install Robot simulator pybullet
!pip install pybullet

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.5/80.5 MB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pybullet: filename=pybullet-3.2.5-cp310-cp310-linux_x86_64.whl size=101451252 sha256=72408c4a83efc3a4fc271b968a073d705f143aec31bb2b617c97c6872b5135d1
  Stored in directory: /root/.cache/pip/wheels/6b/fa/1a/c315a5133f0c9bf202a6daa5d70891120e7fe403e06e3407cc
Successfully built pybullet


In [11]:
import pybullet_envs

# TODO : Render below environments!
# HalfCheetahBulletEnv-v0
# HopperBulletEnv-v0
# HumanoidBulletEnv-v0
# Walker2DBulletEnv-v0

env_id = 'HumanoidBulletEnv-v0'

env = gym.make(env_id)


# Build environment with env ID!
env = gym.make(env_id)
if colab:
    env = wrap_env(env, env_id)

# Initialize environment
observation = env.reset()

for t in range(1000):
    env.render()

    # Randomly sample action from environment
    action = env.action_space.sample()

    # Simulate 1 step
    observation, reward, done, info = env.step(action)

    # done is used to check terminal condition
    if done:
      break;

# Close environment
env.close()

# Render environment
if colab:
    show_video(env_id)

/usr/local/lib/python3.10/dist-packages/gym/envs/registration.py:440: UserWarning: WARN: The `registry.env_specs` property along with `EnvSpecTree` is deprecated. Please use `registry` directly as a dictionary instead.
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/record_video.py:78: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/Colab Notebooks/야

# 2. Run pretrained RL agent within Gym environment

In [12]:
import pybullet_envs
from Humanoid_expert import * # Pretrained model from https://github.com/benelot/pybullet-gym

env_id = 'HumanoidBulletEnv-v0'


# Build environment with env ID!
env = gym.make(env_id)
if colab:
    env = wrap_env(env, env_id)

# Initialize environment
observation = env.reset()

# Call trained policy!
pi = SmallReactivePolicy(env.observation_space, env.action_space)

for t in range(1000):
    env.render()

    # TODO : use policy pi to get action!
    # Hint : policy is mapping from state(observation) to action : pi(a|s)
    action = pi.act(observation)
    # Simulate 1 step
    observation, reward, done, info = env.step(action)

    # done is used to check terminal condition
    if done:
      break;

# Close environment
env.close()

# Render environment
if colab:
    show_video(env_id)

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/record_video.py:78: UserWarning: WARN: Overwriting existing videos at /content/drive/MyDrive/Colab Notebooks/양인순 교수님/setting/video/HumanoidBulletEnv-v0 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_ch

#3. Torch gradient calculation test

In [13]:
import torch

x = torch.randn((5, 5), requires_grad=True)
y = torch.randn((5, 5), requires_grad=True)
z = torch.randn((5, 5), requires_grad=True)

v = (x + y) * z
w = torch.sum(v)

# w = (x + y) * z
w.backward()

# dw / dx  = z
print(z)
print(x.grad)
print('')

# dw / dz  = x + y
print(x+y)
print(z.grad)

tensor([[-0.0937, -1.0260, -0.6100,  0.6064, -0.1174],
        [-0.2522,  0.5726,  0.1015,  0.7778,  0.7922],
        [-1.4534,  0.0030, -0.8203, -1.9670,  0.1293],
        [ 2.1961,  0.3725,  0.2391,  1.8552,  0.3674],
        [-1.3759, -0.5400, -0.8970, -0.4354, -0.9103]], requires_grad=True)
tensor([[-0.0937, -1.0260, -0.6100,  0.6064, -0.1174],
        [-0.2522,  0.5726,  0.1015,  0.7778,  0.7922],
        [-1.4534,  0.0030, -0.8203, -1.9670,  0.1293],
        [ 2.1961,  0.3725,  0.2391,  1.8552,  0.3674],
        [-1.3759, -0.5400, -0.8970, -0.4354, -0.9103]])

tensor([[ 0.5489, -1.4355, -0.5802,  2.9893, -1.1935],
        [-0.9161, -2.0358, -1.2363,  3.1566, -0.9154],
        [-2.9164, -0.5155,  0.3138, -1.1570,  1.2584],
        [-0.5902, -1.8953,  0.7750,  0.5228,  0.2138],
        [-1.1240, -0.0705, -0.1670, -1.7174,  2.4150]], grad_fn=<AddBackward0>)
tensor([[ 0.5489, -1.4355, -0.5802,  2.9893, -1.1935],
        [-0.9161, -2.0358, -1.2363,  3.1566, -0.9154],
        [-2.9164,